@startuml DeploymentDiagramMoveMate

	title Deployment diagram MoveMate



	node "Android Phone" as Client {
		artifact MoveMateApp <<application>>
	}

	cloud FirebaseService

	node Server {


		node WebServer
		artifact MoveMateWebAPI <<executable>>

		database MariaDB

		WebServer --down-- MoveMateWebAPI : "  HTTPS Proxy :5000"
		MoveMateWebAPI --right-- MariaDB

	}




	MoveMateApp --down-- FirebaseService : "  XMPP"
	MoveMateApp --right-- WebServer : "       HTTPS :443            "
	MoveMateWebAPI --left-- FirebaseService : "             HTTPS       "



@enduml